export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:travel_app/View/StartScreen.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:travel_app/model/model.dart';
export 'package:travel_app/View/Home.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:travel_app/View/ViewDetails.dart';
export 'package:travel_app/model/dummyModel.dart';